# Generated by Django 3.2.6 on 2022-01-17 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('age', models.IntegerField(default=30)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('release_date', models.IntegerField(default=1990)),
                ('genre', models.CharField(choices=[('SF', 'SF'), ('Action', 'Action'), ('Comedy', 'Comedy'), ('Drama', 'Drama'), ('Fantasy', 'Fantasy')], max_length=50)),
                ('rating', models.FloatField(default=0)),
                ('running_time', models.IntegerField(blank=True, null=True)),
                ('content', models.TextField()),
                ('director', models.CharField(max_length=20)),
                ('actor', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='poster')),
                ('director2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='review.director')),
            ],
        ),
    ]
